-- 015_rls.sql
-- Row-Level Security (defense in depth).
--
-- The backend uses the service_role key, which BYPASSES RLS — the app is
-- completely unaffected by this migration. RLS blocks direct PostgREST
-- access via user JWTs, preventing a learner from reading another learner's
-- rows even if they craft a valid JWT and query Supabase directly.
--
-- Pattern for learner-owned tables:
--   USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()))
-- auth.uid() is the JWT `sub` claim; user_id is the FK to auth.users.
--
-- Catalog tables (skills, modules) are intentionally left without RLS —
-- they are already read-only for anon/authenticated and contain no PII.

-- ── Enable RLS on every learner-owned / sensitive table ─────────────────────

ALTER TABLE learners           ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_state        ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress           ENABLE ROW LEVEL SECURITY;
ALTER TABLE struggle_signals   ENABLE ROW LEVEL SECURITY;
ALTER TABLE outcomes           ENABLE ROW LEVEL SECURITY;
ALTER TABLE companion_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkin_sessions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles           ENABLE ROW LEVEL SECURITY;
ALTER TABLE instructor_cohorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE rules_config       ENABLE ROW LEVEL SECURITY;

-- ── learners ────────────────────────────────────────────────────────────────
-- SELECT and UPDATE own row only. INSERT is service_role only (signup flow).

CREATE POLICY "learner: select own row"
  ON learners FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "learner: update own row"
  ON learners FOR UPDATE
  USING (user_id = auth.uid());

-- ── skill_state ─────────────────────────────────────────────────────────────

CREATE POLICY "learner: full access to own skill_state"
  ON skill_state FOR ALL
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── progress ────────────────────────────────────────────────────────────────

CREATE POLICY "learner: full access to own progress"
  ON progress FOR ALL
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── struggle_signals ────────────────────────────────────────────────────────
-- SELECT only for learners. INSERT/UPDATE/DELETE stays service_role only —
-- signals are generated by the backend, never by the learner directly.

CREATE POLICY "learner: select own struggle_signals"
  ON struggle_signals FOR SELECT
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── outcomes ────────────────────────────────────────────────────────────────

CREATE POLICY "learner: full access to own outcomes"
  ON outcomes FOR ALL
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── companion_messages ──────────────────────────────────────────────────────

CREATE POLICY "learner: full access to own companion_messages"
  ON companion_messages FOR ALL
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── checkin_sessions ────────────────────────────────────────────────────────

CREATE POLICY "learner: full access to own checkin_sessions"
  ON checkin_sessions FOR ALL
  USING (learner_id IN (SELECT id FROM learners WHERE user_id = auth.uid()));

-- ── profiles ────────────────────────────────────────────────────────────────

CREATE POLICY "user: full access to own profile"
  ON profiles FOR ALL
  USING (id = auth.uid());

-- ── instructor_cohorts ──────────────────────────────────────────────────────
-- Instructors can see their own cohort assignments. Only service_role
-- can manage the mapping.

CREATE POLICY "instructor: select own cohorts"
  ON instructor_cohorts FOR SELECT
  USING (instructor_id = auth.uid());

-- ── rules_config ────────────────────────────────────────────────────────────
-- No policy for authenticated — only service_role (admin tooling) may touch it.
-- Enabling RLS with no policy = deny all authenticated access.
